### signup

POST http://localhost:8000/api/v1/auth/signup HTTP/1.1
Content-Type: application/json

{
  "username": "Tester",
  "password": "test123"
}

### invalid signup 
POST http://localhost:8000/api/v1/auth/signup HTTP/1.1
Content-Type: application/json

{
  "username": "foo",
  "password": ""
}